### ISSUE TITLE
[Feature]: Please add minimap when use GitHub Dark Default theme

### ISSUE THREAD

**Issue by whr3430633** [illixion/vscode-vibrancy-continued#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your idea or feature request

Please add the minimap for GitHub Dark Default theme
![PixPin_2023-12-22_15-55-00](https://github.com/illixion/vscode-vibrancy-continued/assets/52736384/913b3f42-6b87-42b2-bde6-41303c61377b)

**Comment by iSplasher** [comment]
Import a custom css with these rules:
```css
/* Editor minimap */

.monaco-editor .minimap {
    opacity: 0.2 !important;
}

/* Editor scrollbar decorations */

.editor-scrollable > .decorationsOverviewRuler {
    opacity: 0.6 !important;
}
```
