### ISSUE TITLE
[Bug]: workbench startup, zen mode, and some sections aren't transparent

### ISSUE THREAD

**Issue by devCKVargas** [illixion/vscode-vibrancy-continued#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Empty workbench`, toggling `Zen mode` on/off, and `parts of the editor` aren't applying transparency properly.
Check the attached screenshots bellow.

### Expected Behavior

* Disabling Zen mode should bring the transparency back. Or it shouldn't go opaque in general.
* Sticky scroll should have a lower transparency, higher opacity for it to still be distinguishable.

### Steps To Reproduce

* Toggle Zen mode

### Environment

```markdown
- OS: Win11 23H2 (22631.3593)
- VSCode: 1.89.1
- Extension: 1.1.34
- Theme: Catppuccin Mocha
```

### Anything else?

![Code_JojovCvEeb](https://github.com/illixion/vscode-vibrancy-continued/assets/50130192/0c0a7973-7b8f-46c3-a369-6f20338fa0d9)
![Code_OL5yulH7aj](https://github.com/illixion/vscode-vibrancy-continued/assets/50130192/85011cf5-bd4f-4df3-a22b-2194d2b4b6ff)

Similar to: #14 #132
Ignore No. 3 as I forgot about the [**Terminal gpu acceleration**](https://github.com/illixion/vscode-vibrancy-continued?tab=readme-ov-file#effect-doesnt-work-for-terminal)

**Comment by dhruvmachhi** [comment]
I believe #4 is an issue specific to VS Code Pets, and I couldn't find a way to fix the sticky scroll so I just disabled it.

This might help you:
```css
/* Let me know if adding these variables are redundant */
:root {
  --base-background: rgba(30, 30, 46, 0.01) !important;
  --editor-background: transparent !important;
}

.pane-header {
  background-color: var(--base-background) !important;
}

/* I didn't like the scroll background so I hid it, you could try making it more transparent instead*/
.minimap, .editor-scrollable>.decorationsOverviewRuler {
  visibility: hidden;
}

.monaco-editor .sticky-widget {
  /* Find some workaround that can hide the text behind it, I just turned it off for now */
}

/* Couldn't find some way to select the VS Code Pets in CSS to make it transparent.
```
