### ISSUE TITLE
[Feature]: Cursor.com compatibillity

### ISSUE THREAD

**Issue by lainisourgod** [illixion/vscode-vibrancy-continued#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Cursor is a AI-enabled (really cool) VSCode fork and most extensions (e.g. visual ones) are usually working there, but vibrancy does not.

### Describe your idea or feature request

This shouldn't be very hard but would be interesting for me and other folks, considering Cursor is gaining popularity

**Comment by illixion** [comment]
Just tested it, Vibrancy appears to work with no issues, though Cursor has no VSCode Marketplace integration so you have to manually download and install VSIX files: https://www.cursor.com/how-to-install-extension

You'll also be receiving the "installation corrupt" warnings that can't be permanently dismissed, although this can be fixed with this extension: https://marketplace.visualstudio.com/items?itemName=RimuruChan.vscode-fix-checksums-next

**Comment by lainisourgod** [comment]
wow @illixion thanks for your investigation. I'll try it again, because first try didn't work for me

**Comment by lainisourgod** [comment]
![CleanShot 2024-11-27 at 23 41 27@2x](https://github.com/user-attachments/assets/faef1957-bc6c-4e44-92ad-628e8f06af2b)
- I was able to install extension from "Install Extensions" in Cursor (0.42.5) on Mac 
- unfortunately can't do anything to enable vibrancy. In VSCode on same mac runs with default configs
- can't see anything in console 
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/5dc9e4f3-274c-4d59-936d-6d9de9b8e1e6">

**Comment by lainisourgod** [comment]
I disabled apc extension "not sure why it was installed; maybe by cursor?" and vibrancy started working @illixion

**Comment by lainisourgod** [comment]
![CleanShot 2024-11-28 at 01 07 06@2x](https://github.com/user-attachments/assets/28b4ec23-14a6-4573-b2b2-810e84f29f34)

I've tweaked the theme a bit to better use style some other custom elements of cursor (ai chat, composer, control panel). I'm not completely satisfied with the work, but it looks kinda nice with Tokyo Night 

```
.monaco-workbench .part.sidebar > div > div > div > div {
  background-color: var(--vibrancy-soft-background) !important;
}

.monaco-workbench .part.sidebar > div > div > div > div > div:nth-child(2) {
  background-color: var(--vibrancy-soft-background) !important;
}

.quick-input-widget {
  background-color: var(--vibrancy-opaque-background) !important;
}

.full-input-box,
.premium-chat-history-item,
.premium-bubble > div {
  background-color: var(--vibrancy-thin-background) !important;
}

.composer-bar .composer-bar {
  background-color: var(--vibrancy-medium-background) !important;
}

.conversations {
  background-color: var(--vibrancy-opaque-background) !important;
}

.composer-control-panel .composer-bar,
.composer-control-panel .composer-control-panel-sidebar {
  background-color: var(--vibrancy-medium-background) !important;
}

.cursorHintLineWidgetBackground {
  background-color: transparent !important;
}

:root {
  --vscode-commandCenter-inactiveBorder: rgba(157, 157, 157, 0.05);
  --vscode-commandCenter-activeBorder: rgba(204, 204, 204, 0.1);
  --vscode-editorWidget-border: rgba(157, 157, 157, 0.05);
  --vscode-input-border: #252526;
  --vibrancy-thin-background: rgba(37, 37, 38, 0.1);
  --vibrancy-soft-background: rgba(37, 37, 38, 0.3);
  --vibrancy-medium-background: rgba(37, 37, 38, 0.5);
  --vibrancy-hard-background: rgba(24, 24, 24, 0.8);
  --vibrancy-opaque-background: rgba(37, 37, 38, 0.95);
}

.monaco-workbench {
  --vscode-input-background: rgba(37, 37, 38, 0.1);
}

```

**Comment by seanivore** [comment]
oh this is the fix i was looking for

**Comment by KeentGG** [comment]
doesnt work right now. 

<img width="494" alt="Image" src="https://github.com/user-attachments/assets/cda2c2fc-04d3-4789-b720-95004d0cab5a" />.         

Versions

> Cursor Version: 0.45.11
VSCode Version: 1.96.2
Electron: 32.2.6

**Comment by illixion** [comment]
Looks like Cursor hasn't synced with mainline VSCode yet and is still using Electron 32.2.6, which causes a crash on macOS with Vibrancy enabled. I don't follow Cursor's development cycle, but I've submitted a bug report via Cursor and linked the VSCode issue, so hopefully this will be resolved with a future update.

Linked issue: #178

**Comment by pengchzn** [comment]
The latest version of Cursor 0.47.9 has been upgraded to Electron 34.3.4, and the plugin now works correctly!

> doesnt work right now.
> 
> <img alt="Image" width="494" src="https://private-user-images.githubusercontent.com/46834622/416075255-cda2c2fc-04d3-4789-b720-95004d0cab5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI3NDQxNDgsIm5iZiI6MTc0Mjc0Mzg0OCwicGF0aCI6Ii80NjgzNDYyMi80MTYwNzUyNTUtY2RhMmMyZmMtMDRkMy00Nzg5LWI3MjAtOTUwMDRkMGNhYjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzIzVDE1MzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZTNmM2EwMzgzNTc2ZDQ4NDAxNjUyYTIyYzA5YTAyNDdmNmVkZDIzOTQ2MzMxZWFiN2IxNzExYWQ0MDc3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XMYTUoqfMTZgj_-fWIwBMKgmdAdbya-nMLjorBAthLQ">.
> 
> Versions
> 
> > Cursor Version: 0.45.11
> > VSCode Version: 1.96.2
> > Electron: 32.2.6

**Comment by BlinqxRobbieMinderhoud** [comment]
Currently in Cursor

![Image](https://github.com/user-attachments/assets/44bbb25b-19c6-4a82-b0d7-d0146799962b)

**Comment by BlinqxRobbieMinderhoud** [comment]
@lainisourgod 

How do you get your composer to fly out/hover like that? 

https://github.com/illixion/vscode-vibrancy-continued/issues/176#issuecomment-2504793501

**Comment by RobbieMinderhoud** [comment]
@lainisourgod How did you manage to popout the chat window like that? Looks very clean. I would like to replicate it.

https://github.com/illixion/vscode-vibrancy-continued/issues/176#issuecomment-2504793501

**Comment by austinmw** [comment]
In my version of Cursor on Mac the chat window doesn't seem to become transparent. Any idea if this is fixable?

Version: 0.49.3
VSCode Version: 1.96.2
Commit: 224bc1da1a36703c583d62e407d4bccbb8c6a640
Date: 2025-04-21T07:08:50.230Z (9 hrs ago)
Electron: 34.3.4
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.3.0

**Comment by RobbieMinderhoud** [comment]
@austinmw That is because the extension is not officially supported yet for Cursor. But with some custom css, you can get these results. This issue covers such compatibility.

In order to get everything fully transparent myself, I had to introduce some custom css.

![Image](https://github.com/user-attachments/assets/56dc3827-9b83-423f-9a02-c800ef960415)

Follow these steps to get the same results.

> REMINDER! Whenever there is an update. Make sure to call the following 2 commands in order. "Reload Vibrancy" & "Reload Custom CSS and JS"

1. Install the extension [Custom CSS and JS](https://marketplace.cursorapi.com/items?itemName=be5invis.vscode-custom-css)
2. Configure a path for the Custom CSS extension
`    
   "vscode_custom_css.imports": [
        "file://${userHome}/Documents/cursor_vscode_custom.css"
    ],
`
3. Load in the following code into the css file. (REMINDER: This version of the file is not fully completed yet)
`
/* Left Sidebar */
.monaco-workbench .part.sidebar.left#workbench\.parts\.sidebar {
    background-color: var(--vibrancy-thin-background) !important;
    border-right: none !important;
}

/* Left Sidebar */
.monaco-workbench .part.sidebar > div,
.monaco-workbench .part.sidebar > div > div,
.monaco-workbench .part.sidebar > div > div > div,
.monaco-workbench .part.sidebar > div > div > div > div,
.monaco-workbench .part.sidebar > div > div > div > div > div {
    background-color: transparent !important;
}

/* Left Sidebar Menu */
.monaco-workbench .part.sidebar > div > div > div > div > div:nth-child(2) {
    background-color: var(--vibrancy-opaque-background) !important;
}

.quick-input-widget {
    background-color: var(--vibrancy-opaque-background) !important;
}

.composer-control-panel .composer-bar,
.composer-control-panel .composer-control-panel-sidebar {
    background-color: var(--vibrancy-medium-background) !important;
}

.cursorHintLineWidgetBackground {
    background-color: transparent !important;
}

:root {
    --vscode-commandCenter-inactiveBorder: rgba(157, 157, 157, 0.05) !important;
    --vscode-commandCenter-activeBorder: rgba(204, 204, 204, 0.1) !important;
    --vscode-editorWidget-border: rgba(157, 157, 157, 0.05) !important;
    --vscode-input-border: #252526 !important;
    --vibrancy-thin-background: rgba(37, 37, 38, 0.1);
    --vibrancy-soft-background: rgba(37, 37, 38, 0.3);
    --vibrancy-medium-background: rgba(37, 37, 38, 0.5);
    --vibrancy-hard-background: rgba(24, 24, 24, 0.8);
    --vibrancy-opaque-background: rgba(37, 37, 38, 0.95);
}

.monaco-workbench {
    --vscode-editor-background: transparent !important;
    --vscode-multiDiffEditor-headerBackground: transparent !important;
    --vscode-diffEditor-unchangedRegionShadow: transparent !important;
    --vscode-diffEditor-unchangedRegionBackground: transparent !important;
}

.cursorHintLineWidgetBackground {
    background-color: transparent !important;
}

.sticky-widget {
    background-color: var(--vibrancy-medium-background) !important;
}

#workbench\.parts\.titlebar {
    border-bottom: none !important;
}

#workbench\.parts\.auxiliarybar {
    border-left: none !important;
    border-right: none !important;
}

#workbench\.parts\.statusbar {
    --status-border-top-color: none !important;
}

.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab.active {
    --tab-border-top-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar.basepanel.right {
    background-color: var(--vibrancy-thin-background) !important;
}

.monaco-workbench .part.auxiliarybar > .content {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composite.title {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .scrollable-div-container {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .conversations {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar [id^='bubble-'] {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composer-bar {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .full-input-box {
    background-color: var(--vibrancy-soft-background) !important;
}

.monaco-workbench .part.auxiliarybar .empty-pane-message-area {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composer-message-codeblock {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composer-diff-block {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .monaco-editor-background {
    background-color: transparent !important;
}

.multiDiffEditor {
    background-color: transparent !important;
}

`
4. Run the command "Enable Custom CSS and JS"

**Comment by kayg04** [comment]
hey, @RobbieMinderhoud, thank you so much for the css snippet. However, I tried it just now with the latest version of cursor and the window doesn't become transparent or blurred? Did an update break it?

**Comment by RobbieMinderhoud** [comment]
Hi @kayg04,

For me it's still working with the most recent update.

It sounds like custom css is not loading at all. Maybe the file cannot be found. Or maybe you haven't enabled the plugin.

Try the following:
- Enable plugin with command:
![Image](https://github.com/user-attachments/assets/6c9c1713-2809-4673-af22-e46ee7f829d0)
- Reload the custom css plugin right after.
- Try adding something random to the custom css file to see if it is even working.
use this line: `
.monaco-workbench .part.sidebar {
    display: none !important;
}
`
If your sidebar disappears, then it works. Otherwise, probably a path issue.

**Comment by abdorrahmani** [comment]
I have tried all the solutions but when you open two new windows, it only applies to one, and when Windows is up, it works fine.
I use Windows 11.

**Comment by RobbieMinderhoud** [comment]
As I am understanding correctly, it is not working whenever you have 2 windows open?

Could be a Windows thing. Don't really have that problem.

Also. If you put a vage transparent background over another, it is not as transparent as the bottom one.

**Comment by illixion** [comment]
Friendly reminder that using the Custom CSS extension is redundant, as Vibrancy has the same feature that is verified to work, see my earlier comment for how to use it.

@abdorrahmani you may be encountering an issue with “floating windows” as described here: https://github.com/illixion/vscode-vibrancy-continued/issues/115

**Comment by kayg04** [comment]
> Hi [@kayg04](https://github.com/kayg04),
> 
> For me it's still working with the most recent update.
> 
> It sounds like custom css is not loading at all. Maybe the file cannot be found. Or maybe you haven't enabled the plugin.
> 
> Try the following:
> 
>     * Enable plugin with command:
>       ![Image](https://github.com/user-attachments/assets/6c9c1713-2809-4673-af22-e46ee7f829d0)
> 
>     * Reload the custom css plugin right after.
> 
>     * Try adding something random to the custom css file to see if it is even working.
>       use this line: `.monaco-workbench .part.sidebar { display: none !important; }`
>       If your sidebar disappears, then it works. Otherwise, probably a path issue.

hey, thank you, for me since the workbench.html was changed? by custom css and js, vibrancy started working even though custom css and js itself didn't work. It seems that vibrancy doesn't gel well with the particular version of cursor? 

```
Version: 0.49.6
VSCode Version: 1.96.2
Commit: 0781e811de386a0c5bcb07ceb259df8ff8246a50
Date: 2025-04-25T05:07:16.071Z (1 wk ago)
Electron: 34.3.4
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.4.0
```

anyways it's working now but i am happy to reproduce if needed

**Comment by cncn123** [comment]
> [@austinmw](https://github.com/austinmw) That is because the extension is not officially supported yet for Cursor. But with some custom css, you can get these results. This issue covers such compatibility.
> 
> In order to get everything fully transparent myself, I had to introduce some custom css.
> 
> ![Image](https://github.com/user-attachments/assets/56dc3827-9b83-423f-9a02-c800ef960415)
> 
> Follow these steps to get the same results.
> 
> > REMINDER! Whenever there is an update. Make sure to call the following 2 commands in order. "Reload Vibrancy" & "Reload Custom CSS and JS"
> 
> 1. Install the extension [Custom CSS and JS](https://marketplace.cursorapi.com/items?itemName=be5invis.vscode-custom-css)
> 2. Configure a path for the Custom CSS extension
>    `"vscode_custom_css.imports": [ "file://${userHome}/Documents/cursor_vscode_custom.css" ],`
> 3. Load in the following code into the css file. (REMINDER: This version of the file is not fully completed yet)
> 
> ```
> 
> /* Left Sidebar */
> .monaco-workbench .part.sidebar.left#workbench\.parts\.sidebar {
>     background-color: var(--vibrancy-thin-background) !important;
>     border-right: none !important;
> }
> 
> /* Left Sidebar */
> .monaco-workbench .part.sidebar > div,
> .monaco-workbench .part.sidebar > div > div,
> .monaco-workbench .part.sidebar > div > div > div,
> .monaco-workbench .part.sidebar > div > div > div > div,
> .monaco-workbench .part.sidebar > div > div > div > div > div {
>     background-color: transparent !important;
> }
> 
> /* Left Sidebar Menu */
> .monaco-workbench .part.sidebar > div > div > div > div > div:nth-child(2) {
>     background-color: var(--vibrancy-opaque-background) !important;
> }
> 
> .quick-input-widget {
>     background-color: var(--vibrancy-opaque-background) !important;
> }
> 
> .composer-control-panel .composer-bar,
> .composer-control-panel .composer-control-panel-sidebar {
>     background-color: var(--vibrancy-medium-background) !important;
> }
> 
> .cursorHintLineWidgetBackground {
>     background-color: transparent !important;
> }
> 
> :root {
>     --vscode-commandCenter-inactiveBorder: rgba(157, 157, 157, 0.05) !important;
>     --vscode-commandCenter-activeBorder: rgba(204, 204, 204, 0.1) !important;
>     --vscode-editorWidget-border: rgba(157, 157, 157, 0.05) !important;
>     --vscode-input-border: #252526 !important;
>     --vibrancy-thin-background: rgba(37, 37, 38, 0.1);
>     --vibrancy-soft-background: rgba(37, 37, 38, 0.3);
>     --vibrancy-medium-background: rgba(37, 37, 38, 0.5);
>     --vibrancy-hard-background: rgba(24, 24, 24, 0.8);
>     --vibrancy-opaque-background: rgba(37, 37, 38, 0.95);
> }
> 
> .monaco-workbench {
>     --vscode-editor-background: transparent !important;
>     --vscode-multiDiffEditor-headerBackground: transparent !important;
>     --vscode-diffEditor-unchangedRegionShadow: transparent !important;
>     --vscode-diffEditor-unchangedRegionBackground: transparent !important;
> }
> 
> .cursorHintLineWidgetBackground {
>     background-color: transparent !important;
> }
> 
> .sticky-widget {
>     background-color: var(--vibrancy-medium-background) !important;
> }
> 
> #workbench\.parts\.titlebar {
>     border-bottom: none !important;
> }
> 
> #workbench\.parts\.auxiliarybar {
>     border-left: none !important;
>     border-right: none !important;
> }
> 
> #workbench\.parts\.statusbar {
>     --status-border-top-color: none !important;
> }
> 
> .monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab.active {
>     --tab-border-top-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar.basepanel.right {
>     background-color: var(--vibrancy-thin-background) !important;
> }
> 
> .monaco-workbench .part.auxiliarybar > .content {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .composite.title {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .scrollable-div-container {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .conversations {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar [id^='bubble-'] {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .composer-bar {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .full-input-box {
>     background-color: var(--vibrancy-soft-background) !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .empty-pane-message-area {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .composer-message-codeblock {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .composer-diff-block {
>     background-color: transparent !important;
> }
> 
> .monaco-workbench .part.auxiliarybar .monaco-editor-background {
>     background-color: transparent !important;
> }
> 
> .multiDiffEditor {
>     background-color: transparent !important;
> }
> ```
> 
>  4. Run the command "Enable Custom CSS and JS"

**I rewrote css file of @RobbieMinderhoud to support Default Light theme. Any improvements are welcome.** 

![Image](https://github.com/user-attachments/assets/140b9601-d139-4fec-8cd1-9532c1e7f64e)

```css
/* Left Sidebar */
.monaco-workbench .part.sidebar.left#workbench\.parts\.sidebar {
    background-color: transparent !important;
    border-right: none !important;
}

/* Left Sidebar */
.monaco-workbench .part.sidebar > div,
.monaco-workbench .part.sidebar > div > div,
.monaco-workbench .part.sidebar > div > div > div,
.monaco-workbench .part.sidebar > div > div > div > div,
.monaco-workbench .part.sidebar > div > div > div > div > div {
    background-color: transparent !important;
}

/* Left Sidebar Menu */
.monaco-workbench .part.sidebar > div > div > div > div > div:nth-child(2) {
    background-color: var(--vibrancy-thin-background) !important;
}

.quick-input-widget {
    background-color: var(--vibrancy-opaque-background) !important;
}

.composer-control-panel .composer-bar,
.composer-control-panel .composer-control-panel-sidebar {
    background-color: var(--vibrancy-medium-background) !important;
}

.cursorHintLineWidgetBackground {
    background-color: transparent !important;
}

:root {
    --vscode-commandCenter-inactiveBorder: rgba(157, 157, 157, 0.05) !important;
    --vscode-commandCenter-activeBorder: rgba(204, 204, 204, 0.1) !important;
    --vscode-editorWidget-border: rgba(157, 157, 157, 0.05) !important;
    --vscode-input-border: #252526 !important;
    --vibrancy-thin-background: rgba(228, 230, 241, 0.1);
    --vibrancy-soft-background: rgba(3228, 230, 241, 0.3);
    --vibrancy-medium-background: rgba(228, 230, 241, 0.5);
    --vibrancy-hard-background: rgba(228, 230, 241, 0.8);
    --vibrancy-opaque-background: rgba(228, 230, 241, 0.95);
}

.cursorHintLineWidgetBackground {
    background-color: transparent !important;
}

.sticky-widget {
    background-color: var(--vibrancy-hard-background) !important;
}

#workbench\.parts\.titlebar {
    border-bottom: none !important;
}

#workbench\.parts\.auxiliarybar {
    border-left: none !important;
    border-right: none !important;
}

#workbench\.parts\.statusbar {
    --status-border-top-color: none !important;
}

.monaco-workbench
    .part.editor
    > .content
    .editor-group-container
    > .title
    .tabs-container
    > .tab.active {
    --tab-border-top-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar.basepanel.right {
    background-color: var(--vibrancy-thin-background) !important;
}

.monaco-workbench .part.auxiliarybar > .content {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composite.title {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .scrollable-div-container {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .conversations {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar [id^="bubble-"] {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composer-bar {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .full-input-box {
    background-color: var(--vibrancy-soft-background) !important;
}

.monaco-workbench .part.auxiliarybar .empty-pane-message-area {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composer-message-codeblock {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .composer-diff-block {
    background-color: transparent !important;
}

.monaco-workbench .part.auxiliarybar .monaco-editor-background {
    background-color: transparent !important;
}

.multiDiffEditor {
    background-color: transparent !important;
}

```
