### ISSUE TITLE
[Feature]: Tokyo Night Storm without neon effect

### ISSUE THREAD

**Issue by Brachacz** [illixion/vscode-vibrancy-continued#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Vibrancy + Tokyo Night Storm looks marvellous but the neon effect distracts me to the point that I can't use it if I want to be productive. 

### Describe your idea or feature request

Is it possible to add variants of Tokyo Night Storm themes without this effect?

**Comment by littensy** [comment]
You can create a .css file somewhere and add the path to `vscode_vibrancy.imports` in your settings.json. This is what worked for me:

```css
/* /Users/richerd/Documents/Code/tokyo-night-edit.css */
.mtk4,.mtk9.mtk10,.mtk11,.mtk12,.mtk14,.mtk18,.mtk20,.mtk22 {
  text-shadow: 0 0 0, 0 0 0 #0000 !important;
}
```

```json
"vscode_vibrancy.imports": [
    "/Users/richerd/Documents/Code/tokyo-night-edit.css"
]
```
